import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faHouse,
  faUser,
  faEnvelope,
  faArrowRight,
  faArrowUp,
  faCircleCheck,
  faCirclePlus,
  faCircleQuestion,
  faGear,
  faGears,
  faLanguage,
  faMagnifyingGlass,
  faRightFromBracket,
  faComment,
  faFileLines,
  faBell,
  faBook,
  faAt,
  faSquareCheck,
  faPaperclip,
  faMicrophone,
  faListCheck,
  faWaveformLines,
  faUserSecret,
  faFolder,
  faChevronDown,
  faChevronUp,
  faPlus,
  faBars,
  faShareFromSquare,
  faEllipsisVertical,
} from "@fortawesome/pro-solid-svg-icons";
import {
  faSquare,
  faCircle,
  faCirclePlus as faCirclePlusRegular,
  faMagnifyingGlass as faMagnifyingGlassRegular,
  faHouse as faHouseRegular,
  faComment as faCommentRegular,
  faFileLines as faFileLinesRegular,
  faBell as faBellRegular,
  faAt as faAtRegular,
  faCircleQuestion as faCircleQuestionRegular,
  faSquareCheck as faSquareCheckRegular,
  faGears as faGearsRegular,
  faListCheck as faListCheckRegular,
  faBook as faBookRegular,
  faMessages,
  faCheckDouble,
  faShapes,
  faSnooze,
  faPaperclip as faPaperclipRegular,
  faUserSecret as faUserSecretRegular,
  faMicrophone as faMicrophoneRegular,
  faWaveformLines as faWaveformLinesRegular,
  faArrowUp as faArrowUpRegular,
  faFolder as faFolderRegular,
  faChevronDown as faChevronDownRegular,
  faChevronUp as faChevronUpRegular,
  faPlus as faPlusRegular,
  faBars as faBarsRegular,
  faShareFromSquare as faShareFromSquareRegular,
  faEllipsisVertical as faEllipsisVerticalRegular,
  faSidebarFlip as faSidebarFlipRegular,
} from "@fortawesome/pro-regular-svg-icons";

config.autoAddCss = false;

library.add(
  faHouse,
  faUser,
  faEnvelope,
  faArrowRight,
  faArrowUp,
  faCircleCheck,
  faCirclePlus,
  faCircleQuestion,
  faGear,
  faGears,
  faLanguage,
  faMagnifyingGlass,
  faRightFromBracket,
  faComment,
  faFileLines,
  faBell,
  faBook,
  faAt,
  faSquareCheck,
  faPaperclip,
  faMicrophone,
  faListCheck,
  faWaveformLines,
  faUserSecret,
  faSquare,
  faCircle,
  faCirclePlusRegular,
  faMagnifyingGlassRegular,
  faHouseRegular,
  faCommentRegular,
  faFileLinesRegular,
  faBellRegular,
  faAtRegular,
  faCircleQuestionRegular,
  faSquareCheckRegular,
  faGearsRegular,
  faListCheckRegular,
  faBookRegular,
  faMessages,
  faCheckDouble,
  faShapes,
  faSnooze,
  faPaperclipRegular,
  faUserSecretRegular,
  faMicrophoneRegular,
  faWaveformLinesRegular,
  faArrowUpRegular,
  faFolder,
  faChevronDown,
  faChevronUp,
  faPlus,
  faFolderRegular,
  faChevronDownRegular,
  faChevronUpRegular,
  faPlusRegular,
  faBars,
  faBarsRegular,
  faShareFromSquare,
  faShareFromSquareRegular,
  faEllipsisVertical,
  faEllipsisVerticalRegular,
  faSidebarFlipRegular
);
