import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faHouse,
  faUser,
  faEnvelope,
  faArrowRight,
  faArrowUp,
  faCircleCheck,
  faCirclePlus,
  faCircleQuestion,
  faGear,
  faGears,
  faLanguage,
  faMagnifyingGlass,
  faRightFromBracket,
  faComment,
  faFileLines,
  faBell,
  faBook,
  faAt,
  faSquareCheck,
  faPaperclip,
  faMicrophone,
  faListCheck,
  faWaveformLines,
} from "@fortawesome/pro-solid-svg-icons";
import {
  faSquare,
  faCircle,
  faCirclePlus as faCirclePlusRegular,
  faMagnifyingGlass as faMagnifyingGlassRegular,
  faHouse as faHouseRegular,
  faComment as faCommentRegular,
  faFileLines as faFileLinesRegular,
  faBell as faBellRegular,
} from "@fortawesome/pro-regular-svg-icons";

config.autoAddCss = false;

library.add(
  faHouse,
  faUser,
  faEnvelope,
  faArrowRight,
  faArrowUp,
  faCircleCheck,
  faCirclePlus,
  faCircleQuestion,
  faGear,
  faGears,
  faLanguage,
  faMagnifyingGlass,
  faRightFromBracket,
  faComment,
  faFileLines,
  faBell,
  faBook,
  faAt,
  faSquareCheck,
  faPaperclip,
  faMicrophone,
  faListCheck,
  faWaveformLines,
  faSquare,
  faCircle,
  faCirclePlusRegular,
  faMagnifyingGlassRegular,
  faHouseRegular,
  faCommentRegular,
  faFileLinesRegular,
  faBellRegular
);
