import type { Metadata } from "next";
import "@fontsource/google-sans-flex/400.css";
import "@fontsource/google-sans-flex/500.css";
import "@fontsource/google-sans-flex/600.css";
import "@fontsource/google-sans-flex/700.css";
import { ChatProvider } from "@/lib/chat-context";
import { HomeShell } from "@/components/home-shell";
import "@/lib/fontawesome";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className="antialiased"
      >
        <ChatProvider>
          <HomeShell>{children}</HomeShell>
        </ChatProvider>
      </body>
    </html>
  );
}
